Add `spec.clusterIP` in values
If we want to expose cassandra as a NodePort, we got
```
Error: UPGRADE FAILED: Service "cassandra" is invalid: spec.clusterIP: Invalid value: "None": may not be set to 'None' for NodePort services
```

because the `spec.clusterIP` is hard coded to 'None'